# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.




jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the client image
      run: docker build -t mahmoudhamra/multi-client:latest -t mahmoudhamra/multi-client:$(git rev-parse HEAD) -f ./client/Dockerfile ./client
    - name: Build the server image
      run: docker build -t mahmoudhamra/multi-server:latest -t mahmoudhamra/multi-client:$(git rev-parse HEAD) -f ./server/Dockerfile ./server
    - name: Build the worker image
      run: docker build -t mahmoudhamra/multi-worker:latest -f -t mahmoudhamra/multi-client:$(git rev-parse HEAD) ./worker/Dockerfile ./worker



    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: push client image to DockerHub
      run: |
        docker push -t mahmoudhamra/multi-client:latest
        docker push -t mahmoudhamra/multi-client:$(git rev-parse HEAD)

    - name: push server image to DockerHub
      run: |
        docker push -t mahmoudhamra/multi-server:latest
        docker push -t mahmoudhamra/multi-server:$(git rev-parse HEAD)

    - name: push worker image to DockerHub
      run: |
        docker push -t mahmoudhamra/multi-worker:latest
        docker push -t mahmoudhamra/multi-worker:$(git rev-parse HEAD)















    # - name: Login to DockerHub Registry
    #   run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin